version: "3"

networks: 
    cbtku-network:
        driver: bridge

services: 
    nginx:
        image: nginx:alpine
        container_name: "${APP_NAME}-nginx"
        restart: unless-stopped
        tty: true
        ports:
            - "${NGINX_HOST_PORT}:${NGINX_DOCKER_CONTAINER_PORT}"
        volumes: 
            - ./src:/var/www/app
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php
            - mysql
        networks: 
            - cbtku-network

    mysql:
        platform: linux/amd64
        image: mysql:5.7.16
        container_name: "${APP_NAME}-mysql"
        restart: unless-stopped
        tty: true
        ports: 
            - "${MYSQL_HOST_PORT}:${MYSQL_DOCKER_CONTAINER_PORT}"
        volumes: 
            - ./mysql:/var/lib/mysql
        environment: 
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            SERVICE_NAME: "${DB_HOST}"
        networks: 
            - cbtku-network

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: "${APP_NAME}-php"
        restart: unless-stopped
        tty: true
        working_dir: /var/www/app
        volumes: 
            - ./src:/var/www/app
        # ports: 
            # - "${PHP_HOST_PORT}:${PHP_DOCKER_CONTAINER_PORT}"
        networks: 
            - cbtku-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        links:
            - mysql:mysql
        ports:
            - "${PMA_HOST_PORT}:${PMA_DOCKER_CONTAINER_PORT}"
        environment:
            MYSQL_USERNAME: "${DB_USERNAME}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            PMA_HOST: "${DB_HOST}"
            PMA_PORT: "${MYSQL_DOCKER_CONTAINER_PORT}"
            UPLOAD_LIMIT: 300M
        networks: 
            - cbtku-network

    supercronic:
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile-cron
        command: "supercronic /crontab"
        env_file:
            - .env
        volumes:
            - './src:/var/www/html'
            - '/etc/nginx/:/etc/nginx/'
        networks:
            - cbtku-network
        depends_on:
            - php
